ports:
  - name: Web App Pyyne
    description: The main application web server
    port: 8080
    onOpen: open-browser

tasks:
  - init: mvn package
    command: mvn exec:java

image: gitpod/workspace-postgres

vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
    - vscjava.vscode-maven@0.21.2
